### ISSUE TITLE
Using gzip data char arrays possible?

### ISSUE THREAD

**Issue by basementmedia2** [DaleGia/ESPStringTemplate#4]
Hi,

is it possible to use this library in combination with gzip data char arrays, e.g.

```
const char pageheader[] PROGMEM = R"=====(
         HERE IS THE HEXADECIMAL CODE
)=====";

and then in the main sketch

void display_root () {
  ESPStringTemplate testTemplate(buffer, sizeof(buffer));
  testTemplate.add_P(pageheader);
  server.send(200, "text/html", buffer);
}
```

Best wishes and by the way: thanx for this great library!

Daniel

**Comment by DaleGia** [comment]
Hi Daniel,

This seems like an interesting use case! I'm not sure if it is possible and do not have much experience with compressed web pages, but if you do manage to get it working let me know!

In practive, all this library is is a string building helper, so I think in theory it is possible.
